# Generated by Django 5.2.3 on 2025-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_bookinghistoryforgame_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghistoryforgame',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='bookinghistoryforgame',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
