# Generated by Django 5.2.3 on 2025-07-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_remove_bookinghistoryforgame_updated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_1_games",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_10",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_10_games",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_2_games",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_3_games",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_4_games",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_5_games",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_6",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_6_games",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_7",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_7_games",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_8",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_8_games",
                to="games.player",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="slot_9",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_9_games",
                to="games.player",
            ),
        ),
    ]
