# Generated by Django 5.2.3 on 2025-07-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_description_alter_game_slot_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
