# Generated by Django 5.2.3 on 2025-08-01 13:15

from django.db import migrations


def add_initial_data(apps, schema_editor):
    my_model = apps.get_model("games", "PlayerStatus")
    my_model.objects.create(player_status="planned")
    my_model.objects.create(player_status="cancelled")
    my_model.objects.create(player_status="reserved")
    my_model.objects.create(player_status="confirmed")


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0014_remove_game_slot_1_remove_game_slot_10_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerstatus",
            old_name="player_status_name",
            new_name="player_status",
        ),
        migrations.RunPython(add_initial_data),
    ]
