# Generated by Django 5.2.3 on 2025-08-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_rename_player_status_name_playerstatus_player_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookinghistoryforgame",
            unique_together=set(),
        ),
    ]
