# Generated by Django 5.2.4 on 2025-11-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0016_alter_bookinghistoryforgame_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("Planned", "Planned"),
                    ("Played", "Played"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Planned",
                max_length=100,
            ),
        ),
    ]
