# Generated by Django 5.2.3 on 2025-11-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_game_status'),
        ('games', '0017_alter_game_status_playerstatusmanager'),
    ]

    operations = [
    ]
