# Generated by Django 5.2.3 on 2025-11-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_alter_playerstatus_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatus',
            name='player_status',
            field=models.CharField(choices=[('planned', 'planned'), ('cancelled', 'cancelled'), ('confirmed', 'confirmed'), ('reserved', 'reserved'), ('resting', 'resting')], default='resting', max_length=50),
        ),
    ]
