# Generated by Django 5.2.4 on 2025-11-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0021_alter_playerstatusmanager_player_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayerStatusManager",
            new_name="PlayerStatus",
        ),
        migrations.RenameField(
            model_name="bookinghistoryforgame",
            old_name="player_status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="playerstatus",
            old_name="player_status",
            new_name="status",
        ),
    ]
