# Generated by Django 5.2.3 on 2025-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0023_remap_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinghistoryforgame",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "planned"),
                    ("cancelled", "cancelled"),
                    ("confirmed", "confirmed"),
                    ("reserved", "reserved"),
                    ("resting", "resting"),
                    ("awaiting", "awaiting"),
                ],
                default="resting",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="playerstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "planned"),
                    ("cancelled", "cancelled"),
                    ("confirmed", "confirmed"),
                    ("reserved", "reserved"),
                    ("resting", "resting"),
                    ("awaiting", "awaiting"),
                ],
                default="resting",
                max_length=50,
            ),
        ),
    ]
