# Generated by Django 5.2.3 on 2025-12-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0024_alter_bookinghistoryforgame_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinghistoryforgame",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("reserved", "Reserved"),
                    ("resting", "Resting"),
                    ("awaiting", "Awaiting"),
                ],
                default="resting",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="playerstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("reserved", "Reserved"),
                    ("resting", "Resting"),
                    ("awaiting", "Awaiting"),
                ],
                default="resting",
                max_length=50,
            ),
        ),
    ]
