# Generated by Django 5.2.3 on 2026-07-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0025_alter_bookinghistoryforgame_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_accountant",
            field=models.BooleanField(default=False),
        ),
    ]
