# Generated by Django 5.2.3 on 2026-02-15 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0026_goalevent_gameplayer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalevent",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
