# Generated by Django 5.2.3 on 2026-02-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0027_alter_goalevent_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GamePlayer",
        ),
    ]
