# Generated by Django 5.2.3 on 2026-08-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0028_delete_gameplayer"),
        ("games", "0028_substitutepayment"),
    ]

    operations = []
