# Generated by Django 5.2.3 on 2026-08-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0026_chatmessage"),
        ("games", "0029_merge_0028_delete_gameplayer_0028_substitutepayment"),
    ]

    operations = []
