# Generated by Django 5.2.3 on 2026-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0030_merge_20260818_2124"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="number_of_players",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
