# Generated by Django 5.2.3 on 2026-08-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0031_game_number_of_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="notifications_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
