# Generated by Django 5.2.3 on 2026-08-26 21:23

from django.db import migrations, models


def rename_reserved_to_standby(apps, schema_editor):
    BookingHistoryForGame = apps.get_model("games", "BookingHistoryForGame")
    PlayerStatus = apps.get_model("games", "PlayerStatus")
    BookingHistoryForGame.objects.filter(status="reserved").update(status="standby")
    PlayerStatus.objects.filter(status="reserved").update(status="standby")


def rename_standby_to_reserved(apps, schema_editor):
    BookingHistoryForGame = apps.get_model("games", "BookingHistoryForGame")
    PlayerStatus = apps.get_model("games", "PlayerStatus")
    BookingHistoryForGame.objects.filter(status="standby").update(status="reserved")
    PlayerStatus.objects.filter(status="standby").update(status="reserved")


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0032_game_notifications_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinghistoryforgame",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("standby", "Standby"),
                    ("resting", "Resting"),
                    ("awaiting", "Awaiting"),
                ],
                default="resting",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="playerstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("cancelled", "Cancelled"),
                    ("confirmed", "Confirmed"),
                    ("standby", "Standby"),
                    ("resting", "Resting"),
                    ("awaiting", "Awaiting"),
                ],
                default="resting",
                max_length=50,
            ),
        ),
        migrations.RunPython(rename_reserved_to_standby, rename_standby_to_reserved),
    ]
