# Generated by Django 5.2.3 on 2026-08-27 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0033_alter_bookinghistoryforgame_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="reminder_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="reminder_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name="game",
            name="reminder_weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                default=1,
            ),
        ),
    ]
