# Generated by Django 5.2.3 on 2026-08-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0034_game_reminder_enabled_game_reminder_sent_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="reminder_weekday",
        ),
    ]
