# Generated by Django 5.2.3 on 2026-08-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0035_remove_game_reminder_weekday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="reminder_time",
        ),
        migrations.AddField(
            model_name="game",
            name="reminder_send_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
