# Generated by Django 5.2.3 on 2026-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0037_backfill_reminder_send_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="standby_reminder_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="standby_reminder_send_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="standby_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
