# Generated by Django 5.2.3 on 2026-08-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0042_remove_game_reminder_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="minimum_players",
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="gamenotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("weekly", "Weekly"),
                    ("standby", "Standby"),
                    ("min_players_check", "Minimum players check"),
                ],
                max_length=20,
            ),
        ),
    ]
