# Generated by Django 5.2.3 on 2025-07-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
