# Generated by Django 5.2.3 on 2025-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pseudo',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
