# Generated by Django 5.2.3 on 2025-07-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_pseudo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pseudo',
            new_name='nickname',
        ),
    ]
