# Generated by Django 5.2.3 on 2025-07-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_email_alter_player_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mobile_number',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
