# Generated by Django 5.2.3 on 2025-07-21 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mobile_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
